repos:
  - repo: https://github.com/jguttman94/pre-commit-gradle
    rev: v0.3.0  # Use the ref you want to point at
    hooks:
      - id: gradle-task
        args: [ --wrapper, --output, ktlintFormat ]
